CREATE USER IF NOT EXISTS 'sudoker'@'localhost' IDENTIFIED BY 'something!';
GRANT ALL PRIVILEGES ON sudoku.* TO 'sudoker'@'localhost';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS sudoku;
USE sudoku;
CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	session_token VARCHAR(255) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	picture BOOLEAN DEFAULT FALSE,
	totalpoints INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dailyRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS weeklyRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS allTimeRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

