CREATE USER IF NOT EXISTS DB_USER@DB_HOST IDENTIFIED BY DB_PASSWORD;
GRANT ALL PRIVILEGES ON DB_NAME.* TO DB_USER@DB_HOST;
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS DB_NAME;
USE DB_NAME;
CREATE TABLE IF NOT EXISTS 'users' (
	id INT PRIMARY KEY,
	username VARCHAR(255),
	password VARCHAR(255),
	email VARCHAR(255),
	done int
);
