CREATE USER IF NOT EXISTS 'DB_USER'@'DB_HOST' IDENTIFIED BY 'DB_PASSWORD';
GRANT ALL PRIVILEGES ON DB_NAME.* TO 'DB_USER'@'DB_HOST';
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS DB_NAME;
USE DB_NAME;
CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	session_token VARCHAR(255) DEFAULT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	picture BOOLEAN DEFAULT FALSE,
	totalpoints INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS dailyRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS weeklyRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS allTimeRanking (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	points INT DEFAULT 0
);

